version: '3'
      
services:
  gallery-app:
    build: ./gallery-app
    depends_on:
      - db
    ports:
      - "80:8080"
    dns: 8.8.8.8  
  db:
    image: postgres:11.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'gallery-app'
      POSTGRES_PASSWORD: 'gallery-app'
      POSTGRES_DB: 'gallery-app'
    volumes:
      - ./gallery-app/src/main/resources/sql:/docker-entrypoint-initdb.d/