FROM tomcat:9.0.16-jre11

#todo: install maven
#todo: copy project source to /source
#todo: build source
#todo: move war to tomcat folder

COPY target/gallery-app.war $CATALINA_HOME/webapps/gallery-app.war